insert into departments.department (name, faculty_id) values ('lectus aliquam sit amet diam in', 4);
insert into departments.department (name, faculty_id) values ('elit ac nulla sed', 3);
insert into departments.department (name, faculty_id) values ('semper sapien a', 4);
insert into departments.department (name, faculty_id) values ('sit amet turpis elementum ligula', 4);
insert into departments.department (name, faculty_id) values ('eu massa donec dapibus duis at', 5);
insert into departments.department (name, faculty_id) values ('dui maecenas tristique est', 5);
insert into departments.department (name, faculty_id) values ('in hac habitasse', 3);
insert into departments.department (name, faculty_id) values ('ullamcorper purus sit amet', 3);
insert into departments.department (name, faculty_id) values ('erat vestibulum sed magna at', 4);
insert into departments.department (name, faculty_id) values ('non pretium quis lectus suspendisse potenti', 5);
insert into departments.department (name, faculty_id) values ('curabitur gravida nisi at', 5);
insert into departments.department (name, faculty_id) values ('cubilia curae nulla dapibus dolor vel', 1);
insert into departments.department (name, faculty_id) values ('odio curabitur convallis duis', 4);
insert into departments.department (name, faculty_id) values ('platea dictumst etiam faucibus', 2);
insert into departments.department (name, faculty_id) values ('eget eleifend luctus ultricies eu nibh', 3);
insert into departments.department (name, faculty_id) values ('in imperdiet et commodo vulputate', 2);
insert into departments.department (name, faculty_id) values ('ipsum primis in', 2);
insert into departments.department (name, faculty_id) values ('semper est quam', 1);
insert into departments.department (name, faculty_id) values ('aliquam erat volutpat', 1);
insert into departments.department (name, faculty_id) values ('id consequat in consequat', 5);
