insert into departments.department (name, faculty_id, url) values ('id luctus nec molestie', 3, 'http://liveinternet.ru/cursus/id/turpis/integer/aliquet.xml');
insert into departments.department (name, faculty_id, url) values ('semper rutrum nulla', 3, null);
insert into departments.department (name, faculty_id, url) values ('fermentum donec ut', 3, 'https://livejournal.com/sollicitudin/ut/suscipit.jpg');
insert into departments.department (name, faculty_id, url) values ('fusce congue diam id ornare imperdiet', 5, 'https://wix.com/quam/suspendisse/potenti/nullam/porttitor/lacus/at.png');
insert into departments.department (name, faculty_id, url) values ('convallis nunc proin at', 2, 'http://umich.edu/cursus/id/turpis/integer/aliquet/massa/id.js');
insert into departments.department (name, faculty_id, url) values ('nulla facilisi cras non velit nec', 3, 'http://biglobe.ne.jp/ultrices/posuere/cubilia/curae/donec/pharetra/magna.xml');
insert into departments.department (name, faculty_id, url) values ('mauris laoreet ut rhoncus', 5, 'https://webnode.com/amet/consectetuer/adipiscing.aspx');
insert into departments.department (name, faculty_id, url) values ('rutrum at lorem integer', 1, 'https://tripadvisor.com/mauris/viverra/diam/vitae/quam/suspendisse.jsp');
insert into departments.department (name, faculty_id, url) values ('ut tellus nulla', 1, 'https://ed.gov/risus.html');
insert into departments.department (name, faculty_id, url) values ('non velit donec diam', 2, 'https://army.mil/blandit/non/interdum/in/ante/vestibulum/ante.json');
insert into departments.department (name, faculty_id, url) values ('phasellus sit amet', 3, 'https://ow.ly/libero/non/mattis/pulvinar/nulla.xml');
insert into departments.department (name, faculty_id, url) values ('potenti in eleifend quam a odio', 4, null);
insert into departments.department (name, faculty_id, url) values ('nunc purus phasellus', 2, 'http://indiatimes.com/nunc/rhoncus/dui/vel.jsp');
insert into departments.department (name, faculty_id, url) values ('ut volutpat sapien arcu sed', 5, 'https://themeforest.net/nec/sem/duis.png');
insert into departments.department (name, faculty_id, url) values ('in faucibus orci luctus et ultrices', 4, null);
insert into departments.department (name, faculty_id, url) values ('at turpis a pede', 2, 'https://printfriendly.com/nunc/purus/phasellus/in.js');
insert into departments.department (name, faculty_id, url) values ('vestibulum ante ipsum', 5, 'https://sogou.com/sit.xml');
insert into departments.department (name, faculty_id, url) values ('sociis natoque penatibus et', 2, 'https://dell.com/ac/nibh/fusce.js');
insert into departments.department (name, faculty_id, url) values ('sagittis dui vel nisl', 4, 'https://senate.gov/commodo/placerat/praesent/blandit.jsp');
insert into departments.department (name, faculty_id, url) values ('libero rutrum ac lobortis', 3, 'https://comcast.net/dolor/morbi/vel/lectus/in/quam.html');
